### ISSUE TITLE
Serial_utils issue when building

### ISSUE THREAD

**Issue by davidcutting** [iscumd/isc_roboteq_hdc2460#1]
When building the package with catkin_make there is an error which shows that the package can not find serial_utils. Upon further inspection, this is a package that is not available as a rosdep on Melodic.

We should consider making it a submodule to prevent people from having to clone serial_utils manually into their catkin workspace. That way it will be pulled with the rest of Mammoth's code.

**Comment by EpicWolverine** [comment]
If you put in an issue now, he may add it by about this time next year https://github.com/wjwwood/serial_utils/issues/1
